FizzBuzz.Web/FizzBuzz.Web/Models/Model.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FizzBuzz.Web.Models
{
    public class Model
    {
        [Display(Name = "Enter Number")]
        [Required(ErrorMessage = "Number is required.")]
        [RegularExpression("([1-9][0-9]*)", ErrorMessage = "Number must be a natural number")]
        public int? Number { get; set; }
        public IPagedList<string> FizzBuzzList { get; set; }
    }
}

FizzBuzz.Web/FizzBuzz.Web/Controllers/FizzBuzzController.cs
using FizzBuzz.Web.Models;
using FizzBuzz.Repository.Interface;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FizzBuzz.Web.Controllers
{
    public class FizzBuzzController : Controller
    {
        // GET: FizzBuzz
        private readonly IFizzBuzzService fizzBuzzService;
        public FizzBuzzController(IFizzBuzzService fizzBuzzService)
        {
            this.fizzBuzzService = fizzBuzzService;
        }

        [HttpGet]
        public ActionResult FizzBuzzTest()
        {
            return View("FizzBuzzTest");
        }

        public ActionResult Search(Model model, int? page)
        {
            if (ModelState.IsValid)
            {
                int pageNumber = page != null ? Convert.ToInt32(page) : 1;
                int pageSize = 10;
                var fizzBuzzList = this.fizzBuzzService.GetList(Convert.ToInt32(model.Number));
                if (fizzBuzzList != null)
                {
                    model.FizzBuzzList = fizzBuzzList.ToPagedList(pageNumber, pageSize);
                }
            }
            return View("FizzBuzzTest", model);
        }

    }
}

FizzBuzz.Web/FizzBuzz.Web/Views/FizzBuzz/FizzBuzzTest.cshtml
@model FizzBuzz.Web.Models.Model
@{
    ViewBag.Title = "FizzBuzzTest";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Search", "FizzBuzz", FormMethod.Get, new { @class = "form-horizontal", role = "form" }))
{
    <h4>FizzBuzz Test</h4>
    <hr />
    @Html.ValidationMessageFor(m => m.Number, "", new { @class = "error" })

    <div class="form-group">
        @Html.LabelFor(m => m.Number, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Number, new { @class = "form-control", required = "required" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn-default" value="Submit" />
        </div>
    </div>
}




@Html.Partial("_Details")

FizzBuzz.Web/FizzBuzz.Web/Views/Shared/_Details.cshtml
@model FizzBuzz.Web.Models.Model
@using PagedList.Mvc

@if (Model != null && Model.FizzBuzzList != null && Model.FizzBuzzList.Count > 0)
{
    <table class="table table-borderless">
        <tr>
            <th>Display value</th>
        </tr>
        @foreach (var item in Model.FizzBuzzList)
        {
            <tr>
                @{
                    <td>
                        <span class="item">@item</span>
                    </td>
                }
            </tr>
        }
    </table>

    <div class="pagination">
        Page @(Model.FizzBuzzList.PageCount < Model.FizzBuzzList.PageNumber ? 0 : Model.FizzBuzzList.PageNumber) of @Model.FizzBuzzList.PageCount

        @Html.PagedListPager(Model.FizzBuzzList, page => Url.Action("Search", new { Number = Model.Number, page }))
    </div>
}

FizzBuzz.Web/FizzBuzz.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                @*<ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>